name: build

on:
  pull_request:
  push:
    branches-ignore:
      - 0.9.3
      - weblate**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config --global user.email "mbastian@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - name: Test site
        run: |
          cd modules/application
          mkdir target
          mkdir target/autoupdate_site
          echo "test" > target/autoupdate_site/test.txt
          mvn validate scm-publish:publish-scm -P push-site
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
