name: build

on:
  pull_request:
  push:
    branches-ignore:
      - 0.9.3
      - weblate**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Update autoupdate content on gh-pages
        run: |
          mkdir target
          mkdir target/autoupdate_site
          echo "test4" > target/autoupdate_site/test.txt
          mvn validate scm-publish:publish-scm -P push-site
        working-directory: modules/application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
